//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Save_Files_Database_EF_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocument
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
        public string UserId { get; set; }
        public int tblUserId { get; set; }
    
        public virtual tblUser tblUser1 { get; set; }
    }
}
